const Sequelize = require('sequelize');

function defineLocation(sequelize) {
  const model = sequelize.define('Location', {
    name: {
      type: Sequelize.STRING,
    },
    postalCode: {
      type: Sequelize.STRING(20),
      unique: true,
    },
    council: {
      type: Sequelize.STRING,
    },
    tier: {
      type: Sequelize.STRING(20),
    },
  });

  const updateableFields = Object.values(model.rawAttributes)
    .filter((r) => !r._autoGenerated && r.field !== 'postalCode')
    .map((r) => r.field);
  model.upsert = async function (values) {
    return await this.bulkCreate(values, { updateOnDuplicate: updateableFields });
  };
  return model;
}

module.exports = {
  defineLocation,
};
